/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsAddressPool struct {
	AddressPoolName string `json:"AddressPoolName"`
	Addresses string `json:"Addresses"`
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	ID int64 `json:"ID"`
	Name string `json:"Name"`
	Namespace string `json:"Namespace"`
	Protocol string `json:"Protocol"`
	Status string `json:"Status"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
