/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsActionLog struct {
	Action string `json:"Action"`
	CreatedAt time.Time `json:"CreatedAt"`
	FinishedAt time.Time `json:"FinishedAt"`
	ID int32 `json:"ID"`
	Message string `json:"Message"`
	NewData string `json:"NewData"`
	OldData string `json:"OldData"`
	Parameter string `json:"Parameter"`
	ResourceIDs string `json:"ResourceIDs"`
	ResourceType string `json:"ResourceType"`
	Status string `json:"Status"`
}
