/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

type RoutesObjectStorageClassRequestParams struct {
	ObjectStorageClass *ObjectStorageClass `json:"object_storage_class"`
}
