/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package smdclient
import (
	"time"
)

type ModelsCephfsSubvolume struct {
	ByteSize int64 `json:"ByteSize"`
	CephfsName string `json:"CephfsName"`
	CephfsSubvolumeGroup *ModelsCephfsSubvolumeGroup `json:"CephfsSubvolumeGroup"`
	CephfsSubvolumeGroupID int64 `json:"CephfsSubvolumeGroupID"`
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	ID int64 `json:"ID"`
	Name string `json:"Name"`
	Passive bool `json:"Passive"`
	Path string `json:"Path"`
	Status string `json:"Status"`
	SubvolumeName string `json:"SubvolumeName"`
	UpdatedAt time.Time `json:"UpdatedAt"`
	UsedByteSize int64 `json:"UsedByteSize"`
}
