/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsCrushRoot struct {
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	ID int32 `json:"ID"`
	Name string `json:"Name"`
	Osds []ModelsOsd `json:"Osds"`
	Parent *ModelsCrushRoot `json:"Parent"`
	ParentID int32 `json:"ParentID"`
	PoolProperty *ModelsPoolProperty `json:"PoolProperty"`
	Status string `json:"Status"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
