/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsPool struct {
	BlockPoolProperty *ModelsPoolProperty `json:"BlockPoolProperty"`
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	ErasureCodeProfile string `json:"ErasureCodeProfile"`
	ID int64 `json:"ID"`
	Name string `json:"Name"`
	Passive bool `json:"Passive"`
	PgAutoscaleMode bool `json:"PgAutoscaleMode"`
	PgNum int64 `json:"PgNum"`
	PoolID int64 `json:"PoolID"`
	PoolName string `json:"PoolName"`
	State string `json:"State"`
	Status string `json:"Status"`
	Type_ string `json:"Type"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
