/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsObjectBucket struct {
	BucketName string `json:"BucketName"`
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	Host string `json:"Host"`
	ID int32 `json:"ID"`
	MaxObjects int64 `json:"MaxObjects"`
	MaxSize string `json:"MaxSize"`
	Name string `json:"Name"`
	ObjectStorageClass *ModelsObjectStorageClass `json:"ObjectStorageClass"`
	ObjectStorageClassID int32 `json:"ObjectStorageClassID"`
	OsUser *ModelsOsUser `json:"OsUser"`
	OsUserID int32 `json:"OsUserID"`
	Port string `json:"Port"`
	Region string `json:"Region"`
	Status string `json:"Status"`
	SubRegion string `json:"SubRegion"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
