/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

type Pool struct {
	BlockPool *RoutesPoolRequestParams `json:"block_pool"`
	Name string `json:"name"`
}
