/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsActionLog struct {
	Action string `json:"Action"`
	AssociatedResource string `json:"AssociatedResource"`
	CreatedAt time.Time `json:"CreatedAt"`
	Data string `json:"Data"`
	DeletedAt string `json:"DeletedAt"`
	ID int64 `json:"ID"`
	Message string `json:"Message"`
	Parameter string `json:"Parameter"`
	ResourceIDs string `json:"ResourceIDs"`
	ResourceType string `json:"ResourceType"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
