/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsCephfsSubvolumeGroup struct {
	Cephfs *ModelsCephfs `json:"Cephfs"`
	CephfsID int64 `json:"CephfsID"`
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	GroupName string `json:"GroupName"`
	ID int64 `json:"ID"`
	Name string `json:"Name"`
	Status string `json:"Status"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
