/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package smdclient
import (
	"time"
)

type ModelsVolume struct {
	ByteSize int64 `json:"ByteSize"`
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	Format int32 `json:"Format"`
	ID int64 `json:"ID"`
	ImageID string `json:"ImageID"`
	Name string `json:"Name"`
	Passvie bool `json:"Passvie"`
	Pool *ModelsPool `json:"Pool"`
	PoolID int64 `json:"PoolID"`
	Status string `json:"Status"`
	UpdatedAt time.Time `json:"UpdatedAt"`
	UsedByteSize int64 `json:"UsedByteSize"`
	VolumeName string `json:"VolumeName"`
}
