/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

type CephNfsExport struct {
	CephNfsId int64 `json:"ceph_nfs_id"`
	CephfsSubvolumeId int64 `json:"cephfs_subvolume_id"`
	Name string `json:"name"`
	PseudoPath string `json:"pseudo_path"`
}
