/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package smdclient
import (
	"time"
)

type ModelsPoolProperty struct {
	CephfsID int64 `json:"CephfsID"`
	CreatedAt time.Time `json:"CreatedAt"`
	CrushRoot *ModelsCrushRoot `json:"CrushRoot"`
	CrushRootID int64 `json:"CrushRootID"`
	DeletedAt string `json:"DeletedAt"`
	ECCodingChunks int64 `json:"ECCodingChunks"`
	ECDataChunks int64 `json:"ECDataChunks"`
	ID int64 `json:"ID"`
	ObjectStoreID int64 `json:"ObjectStoreID"`
	PoolID int64 `json:"PoolID"`
	Replicated int64 `json:"Replicated"`
	Type_ string `json:"Type"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
