/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package smdclient

type RoutesCephNfsExportRequestParams struct {
	CephNfsExport *CephNfsExport `json:"ceph_nfs_export"`
}
