/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package smdclient
import (
	"time"
)

type ModelsHost struct {
	CPUModel string `json:"CPUModel"`
	CPUs int64 `json:"CPUs"`
	Cores int64 `json:"Cores"`
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	HostModel string `json:"HostModel"`
	ID int64 `json:"ID"`
	MemoryMB int64 `json:"MemoryMB"`
	OS string `json:"OS"`
	Serial string `json:"Serial"`
	Type_ string `json:"Type"`
	UpdatedAt time.Time `json:"UpdatedAt"`
	Vendor string `json:"Vendor"`
	AdminIp string `json:"admin_ip"`
	ClusterIp string `json:"cluster_ip"`
	HostName string `json:"host_name"`
	PublicIp string `json:"public_ip"`
}
