/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsPoolProperty struct {
	CreatedAt time.Time `json:"CreatedAt"`
	CrushRoot *ModelsCrushRoot `json:"CrushRoot"`
	CrushRootID int32 `json:"CrushRootID"`
	DeletedAt string `json:"DeletedAt"`
	ECCodingChunks int32 `json:"ECCodingChunks"`
	ECDataChunks int32 `json:"ECDataChunks"`
	ID int32 `json:"ID"`
	ObjectStoreID int32 `json:"ObjectStoreID"`
	Replicated int32 `json:"Replicated"`
	Type_ string `json:"Type"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
