/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package smdclient

type ObjectStore struct {
	DataPool *RoutesPoolRequestParams `json:"data_pool"`
	GatewayInstances int32 `json:"gateway_instances"`
	MetadataPool *RoutesPoolRequestParams `json:"metadata_pool"`
	Name string `json:"name"`
	Port int32 `json:"port"`
	PreservePoolsOnDelete bool `json:"preserve_pools_on_delete"`
	StoreName string `json:"store_name"`
}
