/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsObjectStore struct {
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	GatewayInstances int32 `json:"GatewayInstances"`
	ID int64 `json:"ID"`
	Name string `json:"Name"`
	PoolProperties []ModelsPoolProperty `json:"PoolProperties"`
	Port int32 `json:"Port"`
	PreservePoolsOnDelete bool `json:"PreservePoolsOnDelete"`
	Status string `json:"Status"`
	StoreName string `json:"StoreName"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
