/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsObjectStorageClass struct {
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	ID int32 `json:"ID"`
	Name string `json:"Name"`
	ObjectBuckets []ModelsObjectBucket `json:"ObjectBuckets"`
	ObjectStore *ModelsObjectStore `json:"ObjectStore"`
	ObjectStoreID int32 `json:"ObjectStoreID"`
	Status string `json:"Status"`
	UpdatedAt time.Time `json:"UpdatedAt"`
}
