/*
 * SmdService
 *
 * Resource for managing storage
 *
 * API version: 1.0.0
 * Contact: canzhu@deeproute.ai
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package smdclient

import (
	"time"
)

type ModelsOsUser struct {
	CreatedAt time.Time `json:"CreatedAt"`
	DeletedAt string `json:"DeletedAt"`
	ID int64 `json:"ID"`
	ObjectBuckets []ModelsObjectBucket `json:"ObjectBuckets"`
	UpdatedAt time.Time `json:"UpdatedAt"`
	Ak string `json:"ak"`
	CapBucket string `json:"cap_bucket"`
	CapMetadata string `json:"cap_metadata"`
	CapUsage string `json:"cap_usage"`
	CapUser string `json:"cap_user"`
	CapZone string `json:"cap_zone"`
	MaxBuckets int32 `json:"max_buckets"`
	MaxObjects int64 `json:"max_objects"`
	MaxSize string `json:"max_size"`
	Name string `json:"name"`
	ObjectStore *ModelsObjectStore `json:"object_store"`
	ObjectStoreId int64 `json:"object_store_id"`
	Sk string `json:"sk"`
	Status string `json:"status"`
}
